spring:
  application:
    name: ticketing
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketing
    username: dev
    password: dev
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  data:
    redis:
      host: localhost
      port: 6379
  security:
    user:
      name: dev
      password: dev

server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    health:
      show-details: always
